//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.WebAuthenticationSoap")]
    public interface WebAuthenticationSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAccount", ReplyAction="*")]
        ServiceTest.ServiceReference1.FindAccountResponse FindAccount(ServiceTest.ServiceReference1.FindAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference1.FindAccountResponse> FindAccountAsync(ServiceTest.ServiceReference1.FindAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsEmployee", ReplyAction="*")]
        bool IsEmployee(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsEmployeeAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsClient", ReplyAction="*")]
        bool IsClient(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsClient", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsClientAsync(int userId);
        
        // CODEGEN: Generating message contract since element name details from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateAccount", ReplyAction="*")]
        ServiceTest.ServiceReference1.CreateAccountResponse CreateAccount(ServiceTest.ServiceReference1.CreateAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference1.CreateAccountResponse> CreateAccountAsync(ServiceTest.ServiceReference1.CreateAccountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAccount", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference1.FindAccountRequestBody Body;
        
        public FindAccountRequest() {
        }
        
        public FindAccountRequest(ServiceTest.ServiceReference1.FindAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public FindAccountRequestBody() {
        }
        
        public FindAccountRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference1.FindAccountResponseBody Body;
        
        public FindAccountResponse() {
        }
        
        public FindAccountResponse(ServiceTest.ServiceReference1.FindAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int FindAccountResult;
        
        public FindAccountResponseBody() {
        }
        
        public FindAccountResponseBody(int FindAccountResult) {
            this.FindAccountResult = FindAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAccount", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference1.CreateAccountRequestBody Body;
        
        public CreateAccountRequest() {
        }
        
        public CreateAccountRequest(ServiceTest.ServiceReference1.CreateAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceTest.ServiceReference1.ArrayOfString details;
        
        public CreateAccountRequestBody() {
        }
        
        public CreateAccountRequestBody(ServiceTest.ServiceReference1.ArrayOfString details) {
            this.details = details;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference1.CreateAccountResponseBody Body;
        
        public CreateAccountResponse() {
        }
        
        public CreateAccountResponse(ServiceTest.ServiceReference1.CreateAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateAccountResult;
        
        public CreateAccountResponseBody() {
        }
        
        public CreateAccountResponseBody(bool CreateAccountResult) {
            this.CreateAccountResult = CreateAccountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebAuthenticationSoapChannel : ServiceTest.ServiceReference1.WebAuthenticationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebAuthenticationSoapClient : System.ServiceModel.ClientBase<ServiceTest.ServiceReference1.WebAuthenticationSoap>, ServiceTest.ServiceReference1.WebAuthenticationSoap {
        
        public WebAuthenticationSoapClient() {
        }
        
        public WebAuthenticationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebAuthenticationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebAuthenticationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebAuthenticationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.ServiceReference1.FindAccountResponse ServiceTest.ServiceReference1.WebAuthenticationSoap.FindAccount(ServiceTest.ServiceReference1.FindAccountRequest request) {
            return base.Channel.FindAccount(request);
        }
        
        public int FindAccount(string username, string password) {
            ServiceTest.ServiceReference1.FindAccountRequest inValue = new ServiceTest.ServiceReference1.FindAccountRequest();
            inValue.Body = new ServiceTest.ServiceReference1.FindAccountRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            ServiceTest.ServiceReference1.FindAccountResponse retVal = ((ServiceTest.ServiceReference1.WebAuthenticationSoap)(this)).FindAccount(inValue);
            return retVal.Body.FindAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference1.FindAccountResponse> ServiceTest.ServiceReference1.WebAuthenticationSoap.FindAccountAsync(ServiceTest.ServiceReference1.FindAccountRequest request) {
            return base.Channel.FindAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.ServiceReference1.FindAccountResponse> FindAccountAsync(string username, string password) {
            ServiceTest.ServiceReference1.FindAccountRequest inValue = new ServiceTest.ServiceReference1.FindAccountRequest();
            inValue.Body = new ServiceTest.ServiceReference1.FindAccountRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((ServiceTest.ServiceReference1.WebAuthenticationSoap)(this)).FindAccountAsync(inValue);
        }
        
        public bool IsEmployee(int userId) {
            return base.Channel.IsEmployee(userId);
        }
        
        public System.Threading.Tasks.Task<bool> IsEmployeeAsync(int userId) {
            return base.Channel.IsEmployeeAsync(userId);
        }
        
        public bool IsClient(int userId) {
            return base.Channel.IsClient(userId);
        }
        
        public System.Threading.Tasks.Task<bool> IsClientAsync(int userId) {
            return base.Channel.IsClientAsync(userId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.ServiceReference1.CreateAccountResponse ServiceTest.ServiceReference1.WebAuthenticationSoap.CreateAccount(ServiceTest.ServiceReference1.CreateAccountRequest request) {
            return base.Channel.CreateAccount(request);
        }
        
        public bool CreateAccount(ServiceTest.ServiceReference1.ArrayOfString details) {
            ServiceTest.ServiceReference1.CreateAccountRequest inValue = new ServiceTest.ServiceReference1.CreateAccountRequest();
            inValue.Body = new ServiceTest.ServiceReference1.CreateAccountRequestBody();
            inValue.Body.details = details;
            ServiceTest.ServiceReference1.CreateAccountResponse retVal = ((ServiceTest.ServiceReference1.WebAuthenticationSoap)(this)).CreateAccount(inValue);
            return retVal.Body.CreateAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference1.CreateAccountResponse> ServiceTest.ServiceReference1.WebAuthenticationSoap.CreateAccountAsync(ServiceTest.ServiceReference1.CreateAccountRequest request) {
            return base.Channel.CreateAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.ServiceReference1.CreateAccountResponse> CreateAccountAsync(ServiceTest.ServiceReference1.ArrayOfString details) {
            ServiceTest.ServiceReference1.CreateAccountRequest inValue = new ServiceTest.ServiceReference1.CreateAccountRequest();
            inValue.Body = new ServiceTest.ServiceReference1.CreateAccountRequestBody();
            inValue.Body.details = details;
            return ((ServiceTest.ServiceReference1.WebAuthenticationSoap)(this)).CreateAccountAsync(inValue);
        }
    }
}
