//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.ClientServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ClientServiceReference.WebClientSoap")]
    public interface WebClientSoap {
        
        // CODEGEN: Generating message contract since element name GetAllCinemasResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCinemas", ReplyAction="*")]
        Project.ClientServiceReference.GetAllCinemasResponse GetAllCinemas(Project.ClientServiceReference.GetAllCinemasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllCinemas", ReplyAction="*")]
        System.Threading.Tasks.Task<Project.ClientServiceReference.GetAllCinemasResponse> GetAllCinemasAsync(Project.ClientServiceReference.GetAllCinemasRequest request);
        
        // CODEGEN: Generating message contract since element name cinemaLocation from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCinemaByLocation", ReplyAction="*")]
        Project.ClientServiceReference.GetCinemaByLocationResponse GetCinemaByLocation(Project.ClientServiceReference.GetCinemaByLocationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCinemaByLocation", ReplyAction="*")]
        System.Threading.Tasks.Task<Project.ClientServiceReference.GetCinemaByLocationResponse> GetCinemaByLocationAsync(Project.ClientServiceReference.GetCinemaByLocationRequest request);
        
        // CODEGEN: Generating message contract since element name weekDay from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMoviesDetailsByDay", ReplyAction="*")]
        Project.ClientServiceReference.GetAllMoviesDetailsByDayResponse GetAllMoviesDetailsByDay(Project.ClientServiceReference.GetAllMoviesDetailsByDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMoviesDetailsByDay", ReplyAction="*")]
        System.Threading.Tasks.Task<Project.ClientServiceReference.GetAllMoviesDetailsByDayResponse> GetAllMoviesDetailsByDayAsync(Project.ClientServiceReference.GetAllMoviesDetailsByDayRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMoviesDetailsByName", ReplyAction="*")]
        Project.ClientServiceReference.GetAllMoviesDetailsByNameResponse GetAllMoviesDetailsByName(Project.ClientServiceReference.GetAllMoviesDetailsByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMoviesDetailsByName", ReplyAction="*")]
        System.Threading.Tasks.Task<Project.ClientServiceReference.GetAllMoviesDetailsByNameResponse> GetAllMoviesDetailsByNameAsync(Project.ClientServiceReference.GetAllMoviesDetailsByNameRequest request);
        
        // CODEGEN: Generating message contract since element name details from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateReservation", ReplyAction="*")]
        Project.ClientServiceReference.CreateReservationResponse CreateReservation(Project.ClientServiceReference.CreateReservationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateReservation", ReplyAction="*")]
        System.Threading.Tasks.Task<Project.ClientServiceReference.CreateReservationResponse> CreateReservationAsync(Project.ClientServiceReference.CreateReservationRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllReservationsByUserResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllReservationsByUser", ReplyAction="*")]
        Project.ClientServiceReference.GetAllReservationsByUserResponse GetAllReservationsByUser(Project.ClientServiceReference.GetAllReservationsByUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllReservationsByUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Project.ClientServiceReference.GetAllReservationsByUserResponse> GetAllReservationsByUserAsync(Project.ClientServiceReference.GetAllReservationsByUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteReservation", ReplyAction="*")]
        bool DeleteReservation(int reservationId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteReservation", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteReservationAsync(int reservationId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCinemasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCinemas", Namespace="http://tempuri.org/", Order=0)]
        public Project.ClientServiceReference.GetAllCinemasRequestBody Body;
        
        public GetAllCinemasRequest() {
        }
        
        public GetAllCinemasRequest(Project.ClientServiceReference.GetAllCinemasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllCinemasRequestBody {
        
        public GetAllCinemasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllCinemasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllCinemasResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project.ClientServiceReference.GetAllCinemasResponseBody Body;
        
        public GetAllCinemasResponse() {
        }
        
        public GetAllCinemasResponse(Project.ClientServiceReference.GetAllCinemasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllCinemasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Project.ClientServiceReference.ArrayOfString GetAllCinemasResult;
        
        public GetAllCinemasResponseBody() {
        }
        
        public GetAllCinemasResponseBody(Project.ClientServiceReference.ArrayOfString GetAllCinemasResult) {
            this.GetAllCinemasResult = GetAllCinemasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCinemaByLocationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCinemaByLocation", Namespace="http://tempuri.org/", Order=0)]
        public Project.ClientServiceReference.GetCinemaByLocationRequestBody Body;
        
        public GetCinemaByLocationRequest() {
        }
        
        public GetCinemaByLocationRequest(Project.ClientServiceReference.GetCinemaByLocationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCinemaByLocationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string cinemaLocation;
        
        public GetCinemaByLocationRequestBody() {
        }
        
        public GetCinemaByLocationRequestBody(string cinemaLocation) {
            this.cinemaLocation = cinemaLocation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCinemaByLocationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCinemaByLocationResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project.ClientServiceReference.GetCinemaByLocationResponseBody Body;
        
        public GetCinemaByLocationResponse() {
        }
        
        public GetCinemaByLocationResponse(Project.ClientServiceReference.GetCinemaByLocationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCinemaByLocationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetCinemaByLocationResult;
        
        public GetCinemaByLocationResponseBody() {
        }
        
        public GetCinemaByLocationResponseBody(int GetCinemaByLocationResult) {
            this.GetCinemaByLocationResult = GetCinemaByLocationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMoviesDetailsByDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMoviesDetailsByDay", Namespace="http://tempuri.org/", Order=0)]
        public Project.ClientServiceReference.GetAllMoviesDetailsByDayRequestBody Body;
        
        public GetAllMoviesDetailsByDayRequest() {
        }
        
        public GetAllMoviesDetailsByDayRequest(Project.ClientServiceReference.GetAllMoviesDetailsByDayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllMoviesDetailsByDayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cinemaId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string weekDay;
        
        public GetAllMoviesDetailsByDayRequestBody() {
        }
        
        public GetAllMoviesDetailsByDayRequestBody(int cinemaId, string weekDay) {
            this.cinemaId = cinemaId;
            this.weekDay = weekDay;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMoviesDetailsByDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMoviesDetailsByDayResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project.ClientServiceReference.GetAllMoviesDetailsByDayResponseBody Body;
        
        public GetAllMoviesDetailsByDayResponse() {
        }
        
        public GetAllMoviesDetailsByDayResponse(Project.ClientServiceReference.GetAllMoviesDetailsByDayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllMoviesDetailsByDayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Project.ClientServiceReference.ArrayOfString GetAllMoviesDetailsByDayResult;
        
        public GetAllMoviesDetailsByDayResponseBody() {
        }
        
        public GetAllMoviesDetailsByDayResponseBody(Project.ClientServiceReference.ArrayOfString GetAllMoviesDetailsByDayResult) {
            this.GetAllMoviesDetailsByDayResult = GetAllMoviesDetailsByDayResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMoviesDetailsByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMoviesDetailsByName", Namespace="http://tempuri.org/", Order=0)]
        public Project.ClientServiceReference.GetAllMoviesDetailsByNameRequestBody Body;
        
        public GetAllMoviesDetailsByNameRequest() {
        }
        
        public GetAllMoviesDetailsByNameRequest(Project.ClientServiceReference.GetAllMoviesDetailsByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllMoviesDetailsByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cinemaId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        public GetAllMoviesDetailsByNameRequestBody() {
        }
        
        public GetAllMoviesDetailsByNameRequestBody(int cinemaId, string name) {
            this.cinemaId = cinemaId;
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMoviesDetailsByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMoviesDetailsByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project.ClientServiceReference.GetAllMoviesDetailsByNameResponseBody Body;
        
        public GetAllMoviesDetailsByNameResponse() {
        }
        
        public GetAllMoviesDetailsByNameResponse(Project.ClientServiceReference.GetAllMoviesDetailsByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllMoviesDetailsByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Project.ClientServiceReference.ArrayOfString GetAllMoviesDetailsByNameResult;
        
        public GetAllMoviesDetailsByNameResponseBody() {
        }
        
        public GetAllMoviesDetailsByNameResponseBody(Project.ClientServiceReference.ArrayOfString GetAllMoviesDetailsByNameResult) {
            this.GetAllMoviesDetailsByNameResult = GetAllMoviesDetailsByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateReservationRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateReservation", Namespace="http://tempuri.org/", Order=0)]
        public Project.ClientServiceReference.CreateReservationRequestBody Body;
        
        public CreateReservationRequest() {
        }
        
        public CreateReservationRequest(Project.ClientServiceReference.CreateReservationRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateReservationRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Project.ClientServiceReference.ArrayOfString details;
        
        public CreateReservationRequestBody() {
        }
        
        public CreateReservationRequestBody(Project.ClientServiceReference.ArrayOfString details) {
            this.details = details;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateReservationResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateReservationResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project.ClientServiceReference.CreateReservationResponseBody Body;
        
        public CreateReservationResponse() {
        }
        
        public CreateReservationResponse(Project.ClientServiceReference.CreateReservationResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateReservationResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateReservationResult;
        
        public CreateReservationResponseBody() {
        }
        
        public CreateReservationResponseBody(bool CreateReservationResult) {
            this.CreateReservationResult = CreateReservationResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllReservationsByUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllReservationsByUser", Namespace="http://tempuri.org/", Order=0)]
        public Project.ClientServiceReference.GetAllReservationsByUserRequestBody Body;
        
        public GetAllReservationsByUserRequest() {
        }
        
        public GetAllReservationsByUserRequest(Project.ClientServiceReference.GetAllReservationsByUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllReservationsByUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int userId;
        
        public GetAllReservationsByUserRequestBody() {
        }
        
        public GetAllReservationsByUserRequestBody(int userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllReservationsByUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllReservationsByUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project.ClientServiceReference.GetAllReservationsByUserResponseBody Body;
        
        public GetAllReservationsByUserResponse() {
        }
        
        public GetAllReservationsByUserResponse(Project.ClientServiceReference.GetAllReservationsByUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllReservationsByUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Project.ClientServiceReference.ArrayOfString GetAllReservationsByUserResult;
        
        public GetAllReservationsByUserResponseBody() {
        }
        
        public GetAllReservationsByUserResponseBody(Project.ClientServiceReference.ArrayOfString GetAllReservationsByUserResult) {
            this.GetAllReservationsByUserResult = GetAllReservationsByUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebClientSoapChannel : Project.ClientServiceReference.WebClientSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebClientSoapClient : System.ServiceModel.ClientBase<Project.ClientServiceReference.WebClientSoap>, Project.ClientServiceReference.WebClientSoap {
        
        public WebClientSoapClient() {
        }
        
        public WebClientSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebClientSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebClientSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebClientSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project.ClientServiceReference.GetAllCinemasResponse Project.ClientServiceReference.WebClientSoap.GetAllCinemas(Project.ClientServiceReference.GetAllCinemasRequest request) {
            return base.Channel.GetAllCinemas(request);
        }
        
        public Project.ClientServiceReference.ArrayOfString GetAllCinemas() {
            Project.ClientServiceReference.GetAllCinemasRequest inValue = new Project.ClientServiceReference.GetAllCinemasRequest();
            inValue.Body = new Project.ClientServiceReference.GetAllCinemasRequestBody();
            Project.ClientServiceReference.GetAllCinemasResponse retVal = ((Project.ClientServiceReference.WebClientSoap)(this)).GetAllCinemas(inValue);
            return retVal.Body.GetAllCinemasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project.ClientServiceReference.GetAllCinemasResponse> Project.ClientServiceReference.WebClientSoap.GetAllCinemasAsync(Project.ClientServiceReference.GetAllCinemasRequest request) {
            return base.Channel.GetAllCinemasAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project.ClientServiceReference.GetAllCinemasResponse> GetAllCinemasAsync() {
            Project.ClientServiceReference.GetAllCinemasRequest inValue = new Project.ClientServiceReference.GetAllCinemasRequest();
            inValue.Body = new Project.ClientServiceReference.GetAllCinemasRequestBody();
            return ((Project.ClientServiceReference.WebClientSoap)(this)).GetAllCinemasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project.ClientServiceReference.GetCinemaByLocationResponse Project.ClientServiceReference.WebClientSoap.GetCinemaByLocation(Project.ClientServiceReference.GetCinemaByLocationRequest request) {
            return base.Channel.GetCinemaByLocation(request);
        }
        
        public int GetCinemaByLocation(string cinemaLocation) {
            Project.ClientServiceReference.GetCinemaByLocationRequest inValue = new Project.ClientServiceReference.GetCinemaByLocationRequest();
            inValue.Body = new Project.ClientServiceReference.GetCinemaByLocationRequestBody();
            inValue.Body.cinemaLocation = cinemaLocation;
            Project.ClientServiceReference.GetCinemaByLocationResponse retVal = ((Project.ClientServiceReference.WebClientSoap)(this)).GetCinemaByLocation(inValue);
            return retVal.Body.GetCinemaByLocationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project.ClientServiceReference.GetCinemaByLocationResponse> Project.ClientServiceReference.WebClientSoap.GetCinemaByLocationAsync(Project.ClientServiceReference.GetCinemaByLocationRequest request) {
            return base.Channel.GetCinemaByLocationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project.ClientServiceReference.GetCinemaByLocationResponse> GetCinemaByLocationAsync(string cinemaLocation) {
            Project.ClientServiceReference.GetCinemaByLocationRequest inValue = new Project.ClientServiceReference.GetCinemaByLocationRequest();
            inValue.Body = new Project.ClientServiceReference.GetCinemaByLocationRequestBody();
            inValue.Body.cinemaLocation = cinemaLocation;
            return ((Project.ClientServiceReference.WebClientSoap)(this)).GetCinemaByLocationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project.ClientServiceReference.GetAllMoviesDetailsByDayResponse Project.ClientServiceReference.WebClientSoap.GetAllMoviesDetailsByDay(Project.ClientServiceReference.GetAllMoviesDetailsByDayRequest request) {
            return base.Channel.GetAllMoviesDetailsByDay(request);
        }
        
        public Project.ClientServiceReference.ArrayOfString GetAllMoviesDetailsByDay(int cinemaId, string weekDay) {
            Project.ClientServiceReference.GetAllMoviesDetailsByDayRequest inValue = new Project.ClientServiceReference.GetAllMoviesDetailsByDayRequest();
            inValue.Body = new Project.ClientServiceReference.GetAllMoviesDetailsByDayRequestBody();
            inValue.Body.cinemaId = cinemaId;
            inValue.Body.weekDay = weekDay;
            Project.ClientServiceReference.GetAllMoviesDetailsByDayResponse retVal = ((Project.ClientServiceReference.WebClientSoap)(this)).GetAllMoviesDetailsByDay(inValue);
            return retVal.Body.GetAllMoviesDetailsByDayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project.ClientServiceReference.GetAllMoviesDetailsByDayResponse> Project.ClientServiceReference.WebClientSoap.GetAllMoviesDetailsByDayAsync(Project.ClientServiceReference.GetAllMoviesDetailsByDayRequest request) {
            return base.Channel.GetAllMoviesDetailsByDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project.ClientServiceReference.GetAllMoviesDetailsByDayResponse> GetAllMoviesDetailsByDayAsync(int cinemaId, string weekDay) {
            Project.ClientServiceReference.GetAllMoviesDetailsByDayRequest inValue = new Project.ClientServiceReference.GetAllMoviesDetailsByDayRequest();
            inValue.Body = new Project.ClientServiceReference.GetAllMoviesDetailsByDayRequestBody();
            inValue.Body.cinemaId = cinemaId;
            inValue.Body.weekDay = weekDay;
            return ((Project.ClientServiceReference.WebClientSoap)(this)).GetAllMoviesDetailsByDayAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project.ClientServiceReference.GetAllMoviesDetailsByNameResponse Project.ClientServiceReference.WebClientSoap.GetAllMoviesDetailsByName(Project.ClientServiceReference.GetAllMoviesDetailsByNameRequest request) {
            return base.Channel.GetAllMoviesDetailsByName(request);
        }
        
        public Project.ClientServiceReference.ArrayOfString GetAllMoviesDetailsByName(int cinemaId, string name) {
            Project.ClientServiceReference.GetAllMoviesDetailsByNameRequest inValue = new Project.ClientServiceReference.GetAllMoviesDetailsByNameRequest();
            inValue.Body = new Project.ClientServiceReference.GetAllMoviesDetailsByNameRequestBody();
            inValue.Body.cinemaId = cinemaId;
            inValue.Body.name = name;
            Project.ClientServiceReference.GetAllMoviesDetailsByNameResponse retVal = ((Project.ClientServiceReference.WebClientSoap)(this)).GetAllMoviesDetailsByName(inValue);
            return retVal.Body.GetAllMoviesDetailsByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project.ClientServiceReference.GetAllMoviesDetailsByNameResponse> Project.ClientServiceReference.WebClientSoap.GetAllMoviesDetailsByNameAsync(Project.ClientServiceReference.GetAllMoviesDetailsByNameRequest request) {
            return base.Channel.GetAllMoviesDetailsByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project.ClientServiceReference.GetAllMoviesDetailsByNameResponse> GetAllMoviesDetailsByNameAsync(int cinemaId, string name) {
            Project.ClientServiceReference.GetAllMoviesDetailsByNameRequest inValue = new Project.ClientServiceReference.GetAllMoviesDetailsByNameRequest();
            inValue.Body = new Project.ClientServiceReference.GetAllMoviesDetailsByNameRequestBody();
            inValue.Body.cinemaId = cinemaId;
            inValue.Body.name = name;
            return ((Project.ClientServiceReference.WebClientSoap)(this)).GetAllMoviesDetailsByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project.ClientServiceReference.CreateReservationResponse Project.ClientServiceReference.WebClientSoap.CreateReservation(Project.ClientServiceReference.CreateReservationRequest request) {
            return base.Channel.CreateReservation(request);
        }
        
        public bool CreateReservation(Project.ClientServiceReference.ArrayOfString details) {
            Project.ClientServiceReference.CreateReservationRequest inValue = new Project.ClientServiceReference.CreateReservationRequest();
            inValue.Body = new Project.ClientServiceReference.CreateReservationRequestBody();
            inValue.Body.details = details;
            Project.ClientServiceReference.CreateReservationResponse retVal = ((Project.ClientServiceReference.WebClientSoap)(this)).CreateReservation(inValue);
            return retVal.Body.CreateReservationResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project.ClientServiceReference.CreateReservationResponse> Project.ClientServiceReference.WebClientSoap.CreateReservationAsync(Project.ClientServiceReference.CreateReservationRequest request) {
            return base.Channel.CreateReservationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project.ClientServiceReference.CreateReservationResponse> CreateReservationAsync(Project.ClientServiceReference.ArrayOfString details) {
            Project.ClientServiceReference.CreateReservationRequest inValue = new Project.ClientServiceReference.CreateReservationRequest();
            inValue.Body = new Project.ClientServiceReference.CreateReservationRequestBody();
            inValue.Body.details = details;
            return ((Project.ClientServiceReference.WebClientSoap)(this)).CreateReservationAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project.ClientServiceReference.GetAllReservationsByUserResponse Project.ClientServiceReference.WebClientSoap.GetAllReservationsByUser(Project.ClientServiceReference.GetAllReservationsByUserRequest request) {
            return base.Channel.GetAllReservationsByUser(request);
        }
        
        public Project.ClientServiceReference.ArrayOfString GetAllReservationsByUser(int userId) {
            Project.ClientServiceReference.GetAllReservationsByUserRequest inValue = new Project.ClientServiceReference.GetAllReservationsByUserRequest();
            inValue.Body = new Project.ClientServiceReference.GetAllReservationsByUserRequestBody();
            inValue.Body.userId = userId;
            Project.ClientServiceReference.GetAllReservationsByUserResponse retVal = ((Project.ClientServiceReference.WebClientSoap)(this)).GetAllReservationsByUser(inValue);
            return retVal.Body.GetAllReservationsByUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project.ClientServiceReference.GetAllReservationsByUserResponse> Project.ClientServiceReference.WebClientSoap.GetAllReservationsByUserAsync(Project.ClientServiceReference.GetAllReservationsByUserRequest request) {
            return base.Channel.GetAllReservationsByUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project.ClientServiceReference.GetAllReservationsByUserResponse> GetAllReservationsByUserAsync(int userId) {
            Project.ClientServiceReference.GetAllReservationsByUserRequest inValue = new Project.ClientServiceReference.GetAllReservationsByUserRequest();
            inValue.Body = new Project.ClientServiceReference.GetAllReservationsByUserRequestBody();
            inValue.Body.userId = userId;
            return ((Project.ClientServiceReference.WebClientSoap)(this)).GetAllReservationsByUserAsync(inValue);
        }
        
        public bool DeleteReservation(int reservationId) {
            return base.Channel.DeleteReservation(reservationId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteReservationAsync(int reservationId) {
            return base.Channel.DeleteReservationAsync(reservationId);
        }
    }
}
