//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.AuthenticationServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuthenticationServiceReference.WebAuthenticationSoap")]
    public interface WebAuthenticationSoap {
        
        // CODEGEN: Generating message contract since element name username from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAccount", ReplyAction="*")]
        Project.AuthenticationServiceReference.FindAccountResponse FindAccount(Project.AuthenticationServiceReference.FindAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<Project.AuthenticationServiceReference.FindAccountResponse> FindAccountAsync(Project.AuthenticationServiceReference.FindAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsEmployee", ReplyAction="*")]
        bool IsEmployee(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsEmployee", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsEmployeeAsync(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsClient", ReplyAction="*")]
        bool IsClient(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsClient", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> IsClientAsync(int userId);
        
        // CODEGEN: Generating message contract since element name details from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateAccount", ReplyAction="*")]
        Project.AuthenticationServiceReference.CreateAccountResponse CreateAccount(Project.AuthenticationServiceReference.CreateAccountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateAccount", ReplyAction="*")]
        System.Threading.Tasks.Task<Project.AuthenticationServiceReference.CreateAccountResponse> CreateAccountAsync(Project.AuthenticationServiceReference.CreateAccountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAccount", Namespace="http://tempuri.org/", Order=0)]
        public Project.AuthenticationServiceReference.FindAccountRequestBody Body;
        
        public FindAccountRequest() {
        }
        
        public FindAccountRequest(Project.AuthenticationServiceReference.FindAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public FindAccountRequestBody() {
        }
        
        public FindAccountRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project.AuthenticationServiceReference.FindAccountResponseBody Body;
        
        public FindAccountResponse() {
        }
        
        public FindAccountResponse(Project.AuthenticationServiceReference.FindAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int FindAccountResult;
        
        public FindAccountResponseBody() {
        }
        
        public FindAccountResponseBody(int FindAccountResult) {
            this.FindAccountResult = FindAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccountRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAccount", Namespace="http://tempuri.org/", Order=0)]
        public Project.AuthenticationServiceReference.CreateAccountRequestBody Body;
        
        public CreateAccountRequest() {
        }
        
        public CreateAccountRequest(Project.AuthenticationServiceReference.CreateAccountRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateAccountRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Project.AuthenticationServiceReference.ArrayOfString details;
        
        public CreateAccountRequestBody() {
        }
        
        public CreateAccountRequestBody(Project.AuthenticationServiceReference.ArrayOfString details) {
            this.details = details;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAccountResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project.AuthenticationServiceReference.CreateAccountResponseBody Body;
        
        public CreateAccountResponse() {
        }
        
        public CreateAccountResponse(Project.AuthenticationServiceReference.CreateAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool CreateAccountResult;
        
        public CreateAccountResponseBody() {
        }
        
        public CreateAccountResponseBody(bool CreateAccountResult) {
            this.CreateAccountResult = CreateAccountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebAuthenticationSoapChannel : Project.AuthenticationServiceReference.WebAuthenticationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebAuthenticationSoapClient : System.ServiceModel.ClientBase<Project.AuthenticationServiceReference.WebAuthenticationSoap>, Project.AuthenticationServiceReference.WebAuthenticationSoap {
        
        public WebAuthenticationSoapClient() {
        }
        
        public WebAuthenticationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebAuthenticationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebAuthenticationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebAuthenticationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project.AuthenticationServiceReference.FindAccountResponse Project.AuthenticationServiceReference.WebAuthenticationSoap.FindAccount(Project.AuthenticationServiceReference.FindAccountRequest request) {
            return base.Channel.FindAccount(request);
        }
        
        public int FindAccount(string username, string password) {
            Project.AuthenticationServiceReference.FindAccountRequest inValue = new Project.AuthenticationServiceReference.FindAccountRequest();
            inValue.Body = new Project.AuthenticationServiceReference.FindAccountRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            Project.AuthenticationServiceReference.FindAccountResponse retVal = ((Project.AuthenticationServiceReference.WebAuthenticationSoap)(this)).FindAccount(inValue);
            return retVal.Body.FindAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project.AuthenticationServiceReference.FindAccountResponse> Project.AuthenticationServiceReference.WebAuthenticationSoap.FindAccountAsync(Project.AuthenticationServiceReference.FindAccountRequest request) {
            return base.Channel.FindAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project.AuthenticationServiceReference.FindAccountResponse> FindAccountAsync(string username, string password) {
            Project.AuthenticationServiceReference.FindAccountRequest inValue = new Project.AuthenticationServiceReference.FindAccountRequest();
            inValue.Body = new Project.AuthenticationServiceReference.FindAccountRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((Project.AuthenticationServiceReference.WebAuthenticationSoap)(this)).FindAccountAsync(inValue);
        }
        
        public bool IsEmployee(int userId) {
            return base.Channel.IsEmployee(userId);
        }
        
        public System.Threading.Tasks.Task<bool> IsEmployeeAsync(int userId) {
            return base.Channel.IsEmployeeAsync(userId);
        }
        
        public bool IsClient(int userId) {
            return base.Channel.IsClient(userId);
        }
        
        public System.Threading.Tasks.Task<bool> IsClientAsync(int userId) {
            return base.Channel.IsClientAsync(userId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project.AuthenticationServiceReference.CreateAccountResponse Project.AuthenticationServiceReference.WebAuthenticationSoap.CreateAccount(Project.AuthenticationServiceReference.CreateAccountRequest request) {
            return base.Channel.CreateAccount(request);
        }
        
        public bool CreateAccount(Project.AuthenticationServiceReference.ArrayOfString details) {
            Project.AuthenticationServiceReference.CreateAccountRequest inValue = new Project.AuthenticationServiceReference.CreateAccountRequest();
            inValue.Body = new Project.AuthenticationServiceReference.CreateAccountRequestBody();
            inValue.Body.details = details;
            Project.AuthenticationServiceReference.CreateAccountResponse retVal = ((Project.AuthenticationServiceReference.WebAuthenticationSoap)(this)).CreateAccount(inValue);
            return retVal.Body.CreateAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project.AuthenticationServiceReference.CreateAccountResponse> Project.AuthenticationServiceReference.WebAuthenticationSoap.CreateAccountAsync(Project.AuthenticationServiceReference.CreateAccountRequest request) {
            return base.Channel.CreateAccountAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project.AuthenticationServiceReference.CreateAccountResponse> CreateAccountAsync(Project.AuthenticationServiceReference.ArrayOfString details) {
            Project.AuthenticationServiceReference.CreateAccountRequest inValue = new Project.AuthenticationServiceReference.CreateAccountRequest();
            inValue.Body = new Project.AuthenticationServiceReference.CreateAccountRequestBody();
            inValue.Body.details = details;
            return ((Project.AuthenticationServiceReference.WebAuthenticationSoap)(this)).CreateAccountAsync(inValue);
        }
    }
}
