//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project.AdminServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AdminServiceReference.WebAdminSoap")]
    public interface WebAdminSoap {
        
        // CODEGEN: Generating message contract since element name GetAllMoviesDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMoviesDetails", ReplyAction="*")]
        Project.AdminServiceReference.GetAllMoviesDetailsResponse GetAllMoviesDetails(Project.AdminServiceReference.GetAllMoviesDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMoviesDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<Project.AdminServiceReference.GetAllMoviesDetailsResponse> GetAllMoviesDetailsAsync(Project.AdminServiceReference.GetAllMoviesDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name details from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMovie", ReplyAction="*")]
        Project.AdminServiceReference.AddMovieResponse AddMovie(Project.AdminServiceReference.AddMovieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMovie", ReplyAction="*")]
        System.Threading.Tasks.Task<Project.AdminServiceReference.AddMovieResponse> AddMovieAsync(Project.AdminServiceReference.AddMovieRequest request);
        
        // CODEGEN: Generating message contract since element name details from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMovie", ReplyAction="*")]
        Project.AdminServiceReference.UpdateMovieResponse UpdateMovie(Project.AdminServiceReference.UpdateMovieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMovie", ReplyAction="*")]
        System.Threading.Tasks.Task<Project.AdminServiceReference.UpdateMovieResponse> UpdateMovieAsync(Project.AdminServiceReference.UpdateMovieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMovie", ReplyAction="*")]
        bool DeleteMovie(int movieId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMovie", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteMovieAsync(int movieId);
        
        // CODEGEN: Generating message contract since element name GetAllWorkShiftsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllWorkShifts", ReplyAction="*")]
        Project.AdminServiceReference.GetAllWorkShiftsResponse GetAllWorkShifts(Project.AdminServiceReference.GetAllWorkShiftsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllWorkShifts", ReplyAction="*")]
        System.Threading.Tasks.Task<Project.AdminServiceReference.GetAllWorkShiftsResponse> GetAllWorkShiftsAsync(Project.AdminServiceReference.GetAllWorkShiftsRequest request);
        
        // CODEGEN: Generating message contract since element name details from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddWorkShift", ReplyAction="*")]
        Project.AdminServiceReference.AddWorkShiftResponse AddWorkShift(Project.AdminServiceReference.AddWorkShiftRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddWorkShift", ReplyAction="*")]
        System.Threading.Tasks.Task<Project.AdminServiceReference.AddWorkShiftResponse> AddWorkShiftAsync(Project.AdminServiceReference.AddWorkShiftRequest request);
        
        // CODEGEN: Generating message contract since element name details from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWorkShift", ReplyAction="*")]
        Project.AdminServiceReference.UpdateWorkShiftResponse UpdateWorkShift(Project.AdminServiceReference.UpdateWorkShiftRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWorkShift", ReplyAction="*")]
        System.Threading.Tasks.Task<Project.AdminServiceReference.UpdateWorkShiftResponse> UpdateWorkShiftAsync(Project.AdminServiceReference.UpdateWorkShiftRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteWorkShift", ReplyAction="*")]
        bool DeleteWorkShift(int workShiftId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteWorkShift", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteWorkShiftAsync(int workShiftId);
        
        // CODEGEN: Generating message contract since element name GetAllSchedulesByCinemaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSchedulesByCinema", ReplyAction="*")]
        Project.AdminServiceReference.GetAllSchedulesByCinemaResponse GetAllSchedulesByCinema(Project.AdminServiceReference.GetAllSchedulesByCinemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSchedulesByCinema", ReplyAction="*")]
        System.Threading.Tasks.Task<Project.AdminServiceReference.GetAllSchedulesByCinemaResponse> GetAllSchedulesByCinemaAsync(Project.AdminServiceReference.GetAllSchedulesByCinemaRequest request);
        
        // CODEGEN: Generating message contract since element name details from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSchedules", ReplyAction="*")]
        Project.AdminServiceReference.UpdateSchedulesResponse UpdateSchedules(Project.AdminServiceReference.UpdateSchedulesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSchedules", ReplyAction="*")]
        System.Threading.Tasks.Task<Project.AdminServiceReference.UpdateSchedulesResponse> UpdateSchedulesAsync(Project.AdminServiceReference.UpdateSchedulesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMoviesDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMoviesDetails", Namespace="http://tempuri.org/", Order=0)]
        public Project.AdminServiceReference.GetAllMoviesDetailsRequestBody Body;
        
        public GetAllMoviesDetailsRequest() {
        }
        
        public GetAllMoviesDetailsRequest(Project.AdminServiceReference.GetAllMoviesDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllMoviesDetailsRequestBody {
        
        public GetAllMoviesDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMoviesDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMoviesDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project.AdminServiceReference.GetAllMoviesDetailsResponseBody Body;
        
        public GetAllMoviesDetailsResponse() {
        }
        
        public GetAllMoviesDetailsResponse(Project.AdminServiceReference.GetAllMoviesDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllMoviesDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Project.AdminServiceReference.ArrayOfString GetAllMoviesDetailsResult;
        
        public GetAllMoviesDetailsResponseBody() {
        }
        
        public GetAllMoviesDetailsResponseBody(Project.AdminServiceReference.ArrayOfString GetAllMoviesDetailsResult) {
            this.GetAllMoviesDetailsResult = GetAllMoviesDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMovieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMovie", Namespace="http://tempuri.org/", Order=0)]
        public Project.AdminServiceReference.AddMovieRequestBody Body;
        
        public AddMovieRequest() {
        }
        
        public AddMovieRequest(Project.AdminServiceReference.AddMovieRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMovieRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Project.AdminServiceReference.ArrayOfString details;
        
        public AddMovieRequestBody() {
        }
        
        public AddMovieRequestBody(Project.AdminServiceReference.ArrayOfString details) {
            this.details = details;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMovieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMovieResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project.AdminServiceReference.AddMovieResponseBody Body;
        
        public AddMovieResponse() {
        }
        
        public AddMovieResponse(Project.AdminServiceReference.AddMovieResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMovieResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddMovieResult;
        
        public AddMovieResponseBody() {
        }
        
        public AddMovieResponseBody(bool AddMovieResult) {
            this.AddMovieResult = AddMovieResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMovieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMovie", Namespace="http://tempuri.org/", Order=0)]
        public Project.AdminServiceReference.UpdateMovieRequestBody Body;
        
        public UpdateMovieRequest() {
        }
        
        public UpdateMovieRequest(Project.AdminServiceReference.UpdateMovieRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateMovieRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Project.AdminServiceReference.ArrayOfString details;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int movieId;
        
        public UpdateMovieRequestBody() {
        }
        
        public UpdateMovieRequestBody(Project.AdminServiceReference.ArrayOfString details, int movieId) {
            this.details = details;
            this.movieId = movieId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMovieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMovieResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project.AdminServiceReference.UpdateMovieResponseBody Body;
        
        public UpdateMovieResponse() {
        }
        
        public UpdateMovieResponse(Project.AdminServiceReference.UpdateMovieResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateMovieResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateMovieResult;
        
        public UpdateMovieResponseBody() {
        }
        
        public UpdateMovieResponseBody(bool UpdateMovieResult) {
            this.UpdateMovieResult = UpdateMovieResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllWorkShiftsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllWorkShifts", Namespace="http://tempuri.org/", Order=0)]
        public Project.AdminServiceReference.GetAllWorkShiftsRequestBody Body;
        
        public GetAllWorkShiftsRequest() {
        }
        
        public GetAllWorkShiftsRequest(Project.AdminServiceReference.GetAllWorkShiftsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllWorkShiftsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cinemaId;
        
        public GetAllWorkShiftsRequestBody() {
        }
        
        public GetAllWorkShiftsRequestBody(int cinemaId) {
            this.cinemaId = cinemaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllWorkShiftsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllWorkShiftsResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project.AdminServiceReference.GetAllWorkShiftsResponseBody Body;
        
        public GetAllWorkShiftsResponse() {
        }
        
        public GetAllWorkShiftsResponse(Project.AdminServiceReference.GetAllWorkShiftsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllWorkShiftsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Project.AdminServiceReference.ArrayOfString GetAllWorkShiftsResult;
        
        public GetAllWorkShiftsResponseBody() {
        }
        
        public GetAllWorkShiftsResponseBody(Project.AdminServiceReference.ArrayOfString GetAllWorkShiftsResult) {
            this.GetAllWorkShiftsResult = GetAllWorkShiftsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddWorkShiftRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddWorkShift", Namespace="http://tempuri.org/", Order=0)]
        public Project.AdminServiceReference.AddWorkShiftRequestBody Body;
        
        public AddWorkShiftRequest() {
        }
        
        public AddWorkShiftRequest(Project.AdminServiceReference.AddWorkShiftRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddWorkShiftRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Project.AdminServiceReference.ArrayOfString details;
        
        public AddWorkShiftRequestBody() {
        }
        
        public AddWorkShiftRequestBody(Project.AdminServiceReference.ArrayOfString details) {
            this.details = details;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddWorkShiftResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddWorkShiftResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project.AdminServiceReference.AddWorkShiftResponseBody Body;
        
        public AddWorkShiftResponse() {
        }
        
        public AddWorkShiftResponse(Project.AdminServiceReference.AddWorkShiftResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddWorkShiftResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddWorkShiftResult;
        
        public AddWorkShiftResponseBody() {
        }
        
        public AddWorkShiftResponseBody(bool AddWorkShiftResult) {
            this.AddWorkShiftResult = AddWorkShiftResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateWorkShiftRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateWorkShift", Namespace="http://tempuri.org/", Order=0)]
        public Project.AdminServiceReference.UpdateWorkShiftRequestBody Body;
        
        public UpdateWorkShiftRequest() {
        }
        
        public UpdateWorkShiftRequest(Project.AdminServiceReference.UpdateWorkShiftRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateWorkShiftRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Project.AdminServiceReference.ArrayOfString details;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int workShiftId;
        
        public UpdateWorkShiftRequestBody() {
        }
        
        public UpdateWorkShiftRequestBody(Project.AdminServiceReference.ArrayOfString details, int workShiftId) {
            this.details = details;
            this.workShiftId = workShiftId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateWorkShiftResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateWorkShiftResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project.AdminServiceReference.UpdateWorkShiftResponseBody Body;
        
        public UpdateWorkShiftResponse() {
        }
        
        public UpdateWorkShiftResponse(Project.AdminServiceReference.UpdateWorkShiftResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateWorkShiftResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateWorkShiftResult;
        
        public UpdateWorkShiftResponseBody() {
        }
        
        public UpdateWorkShiftResponseBody(bool UpdateWorkShiftResult) {
            this.UpdateWorkShiftResult = UpdateWorkShiftResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSchedulesByCinemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSchedulesByCinema", Namespace="http://tempuri.org/", Order=0)]
        public Project.AdminServiceReference.GetAllSchedulesByCinemaRequestBody Body;
        
        public GetAllSchedulesByCinemaRequest() {
        }
        
        public GetAllSchedulesByCinemaRequest(Project.AdminServiceReference.GetAllSchedulesByCinemaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllSchedulesByCinemaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cinemaId;
        
        public GetAllSchedulesByCinemaRequestBody() {
        }
        
        public GetAllSchedulesByCinemaRequestBody(int cinemaId) {
            this.cinemaId = cinemaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSchedulesByCinemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSchedulesByCinemaResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project.AdminServiceReference.GetAllSchedulesByCinemaResponseBody Body;
        
        public GetAllSchedulesByCinemaResponse() {
        }
        
        public GetAllSchedulesByCinemaResponse(Project.AdminServiceReference.GetAllSchedulesByCinemaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllSchedulesByCinemaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Project.AdminServiceReference.ArrayOfString GetAllSchedulesByCinemaResult;
        
        public GetAllSchedulesByCinemaResponseBody() {
        }
        
        public GetAllSchedulesByCinemaResponseBody(Project.AdminServiceReference.ArrayOfString GetAllSchedulesByCinemaResult) {
            this.GetAllSchedulesByCinemaResult = GetAllSchedulesByCinemaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSchedulesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSchedules", Namespace="http://tempuri.org/", Order=0)]
        public Project.AdminServiceReference.UpdateSchedulesRequestBody Body;
        
        public UpdateSchedulesRequest() {
        }
        
        public UpdateSchedulesRequest(Project.AdminServiceReference.UpdateSchedulesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSchedulesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Project.AdminServiceReference.ArrayOfString details;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int scheduleId;
        
        public UpdateSchedulesRequestBody() {
        }
        
        public UpdateSchedulesRequestBody(Project.AdminServiceReference.ArrayOfString details, int scheduleId) {
            this.details = details;
            this.scheduleId = scheduleId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSchedulesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSchedulesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Project.AdminServiceReference.UpdateSchedulesResponseBody Body;
        
        public UpdateSchedulesResponse() {
        }
        
        public UpdateSchedulesResponse(Project.AdminServiceReference.UpdateSchedulesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSchedulesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateSchedulesResult;
        
        public UpdateSchedulesResponseBody() {
        }
        
        public UpdateSchedulesResponseBody(bool UpdateSchedulesResult) {
            this.UpdateSchedulesResult = UpdateSchedulesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebAdminSoapChannel : Project.AdminServiceReference.WebAdminSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebAdminSoapClient : System.ServiceModel.ClientBase<Project.AdminServiceReference.WebAdminSoap>, Project.AdminServiceReference.WebAdminSoap {
        
        public WebAdminSoapClient() {
        }
        
        public WebAdminSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebAdminSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebAdminSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebAdminSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project.AdminServiceReference.GetAllMoviesDetailsResponse Project.AdminServiceReference.WebAdminSoap.GetAllMoviesDetails(Project.AdminServiceReference.GetAllMoviesDetailsRequest request) {
            return base.Channel.GetAllMoviesDetails(request);
        }
        
        public Project.AdminServiceReference.ArrayOfString GetAllMoviesDetails() {
            Project.AdminServiceReference.GetAllMoviesDetailsRequest inValue = new Project.AdminServiceReference.GetAllMoviesDetailsRequest();
            inValue.Body = new Project.AdminServiceReference.GetAllMoviesDetailsRequestBody();
            Project.AdminServiceReference.GetAllMoviesDetailsResponse retVal = ((Project.AdminServiceReference.WebAdminSoap)(this)).GetAllMoviesDetails(inValue);
            return retVal.Body.GetAllMoviesDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project.AdminServiceReference.GetAllMoviesDetailsResponse> Project.AdminServiceReference.WebAdminSoap.GetAllMoviesDetailsAsync(Project.AdminServiceReference.GetAllMoviesDetailsRequest request) {
            return base.Channel.GetAllMoviesDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project.AdminServiceReference.GetAllMoviesDetailsResponse> GetAllMoviesDetailsAsync() {
            Project.AdminServiceReference.GetAllMoviesDetailsRequest inValue = new Project.AdminServiceReference.GetAllMoviesDetailsRequest();
            inValue.Body = new Project.AdminServiceReference.GetAllMoviesDetailsRequestBody();
            return ((Project.AdminServiceReference.WebAdminSoap)(this)).GetAllMoviesDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project.AdminServiceReference.AddMovieResponse Project.AdminServiceReference.WebAdminSoap.AddMovie(Project.AdminServiceReference.AddMovieRequest request) {
            return base.Channel.AddMovie(request);
        }
        
        public bool AddMovie(Project.AdminServiceReference.ArrayOfString details) {
            Project.AdminServiceReference.AddMovieRequest inValue = new Project.AdminServiceReference.AddMovieRequest();
            inValue.Body = new Project.AdminServiceReference.AddMovieRequestBody();
            inValue.Body.details = details;
            Project.AdminServiceReference.AddMovieResponse retVal = ((Project.AdminServiceReference.WebAdminSoap)(this)).AddMovie(inValue);
            return retVal.Body.AddMovieResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project.AdminServiceReference.AddMovieResponse> Project.AdminServiceReference.WebAdminSoap.AddMovieAsync(Project.AdminServiceReference.AddMovieRequest request) {
            return base.Channel.AddMovieAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project.AdminServiceReference.AddMovieResponse> AddMovieAsync(Project.AdminServiceReference.ArrayOfString details) {
            Project.AdminServiceReference.AddMovieRequest inValue = new Project.AdminServiceReference.AddMovieRequest();
            inValue.Body = new Project.AdminServiceReference.AddMovieRequestBody();
            inValue.Body.details = details;
            return ((Project.AdminServiceReference.WebAdminSoap)(this)).AddMovieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project.AdminServiceReference.UpdateMovieResponse Project.AdminServiceReference.WebAdminSoap.UpdateMovie(Project.AdminServiceReference.UpdateMovieRequest request) {
            return base.Channel.UpdateMovie(request);
        }
        
        public bool UpdateMovie(Project.AdminServiceReference.ArrayOfString details, int movieId) {
            Project.AdminServiceReference.UpdateMovieRequest inValue = new Project.AdminServiceReference.UpdateMovieRequest();
            inValue.Body = new Project.AdminServiceReference.UpdateMovieRequestBody();
            inValue.Body.details = details;
            inValue.Body.movieId = movieId;
            Project.AdminServiceReference.UpdateMovieResponse retVal = ((Project.AdminServiceReference.WebAdminSoap)(this)).UpdateMovie(inValue);
            return retVal.Body.UpdateMovieResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project.AdminServiceReference.UpdateMovieResponse> Project.AdminServiceReference.WebAdminSoap.UpdateMovieAsync(Project.AdminServiceReference.UpdateMovieRequest request) {
            return base.Channel.UpdateMovieAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project.AdminServiceReference.UpdateMovieResponse> UpdateMovieAsync(Project.AdminServiceReference.ArrayOfString details, int movieId) {
            Project.AdminServiceReference.UpdateMovieRequest inValue = new Project.AdminServiceReference.UpdateMovieRequest();
            inValue.Body = new Project.AdminServiceReference.UpdateMovieRequestBody();
            inValue.Body.details = details;
            inValue.Body.movieId = movieId;
            return ((Project.AdminServiceReference.WebAdminSoap)(this)).UpdateMovieAsync(inValue);
        }
        
        public bool DeleteMovie(int movieId) {
            return base.Channel.DeleteMovie(movieId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteMovieAsync(int movieId) {
            return base.Channel.DeleteMovieAsync(movieId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project.AdminServiceReference.GetAllWorkShiftsResponse Project.AdminServiceReference.WebAdminSoap.GetAllWorkShifts(Project.AdminServiceReference.GetAllWorkShiftsRequest request) {
            return base.Channel.GetAllWorkShifts(request);
        }
        
        public Project.AdminServiceReference.ArrayOfString GetAllWorkShifts(int cinemaId) {
            Project.AdminServiceReference.GetAllWorkShiftsRequest inValue = new Project.AdminServiceReference.GetAllWorkShiftsRequest();
            inValue.Body = new Project.AdminServiceReference.GetAllWorkShiftsRequestBody();
            inValue.Body.cinemaId = cinemaId;
            Project.AdminServiceReference.GetAllWorkShiftsResponse retVal = ((Project.AdminServiceReference.WebAdminSoap)(this)).GetAllWorkShifts(inValue);
            return retVal.Body.GetAllWorkShiftsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project.AdminServiceReference.GetAllWorkShiftsResponse> Project.AdminServiceReference.WebAdminSoap.GetAllWorkShiftsAsync(Project.AdminServiceReference.GetAllWorkShiftsRequest request) {
            return base.Channel.GetAllWorkShiftsAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project.AdminServiceReference.GetAllWorkShiftsResponse> GetAllWorkShiftsAsync(int cinemaId) {
            Project.AdminServiceReference.GetAllWorkShiftsRequest inValue = new Project.AdminServiceReference.GetAllWorkShiftsRequest();
            inValue.Body = new Project.AdminServiceReference.GetAllWorkShiftsRequestBody();
            inValue.Body.cinemaId = cinemaId;
            return ((Project.AdminServiceReference.WebAdminSoap)(this)).GetAllWorkShiftsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project.AdminServiceReference.AddWorkShiftResponse Project.AdminServiceReference.WebAdminSoap.AddWorkShift(Project.AdminServiceReference.AddWorkShiftRequest request) {
            return base.Channel.AddWorkShift(request);
        }
        
        public bool AddWorkShift(Project.AdminServiceReference.ArrayOfString details) {
            Project.AdminServiceReference.AddWorkShiftRequest inValue = new Project.AdminServiceReference.AddWorkShiftRequest();
            inValue.Body = new Project.AdminServiceReference.AddWorkShiftRequestBody();
            inValue.Body.details = details;
            Project.AdminServiceReference.AddWorkShiftResponse retVal = ((Project.AdminServiceReference.WebAdminSoap)(this)).AddWorkShift(inValue);
            return retVal.Body.AddWorkShiftResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project.AdminServiceReference.AddWorkShiftResponse> Project.AdminServiceReference.WebAdminSoap.AddWorkShiftAsync(Project.AdminServiceReference.AddWorkShiftRequest request) {
            return base.Channel.AddWorkShiftAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project.AdminServiceReference.AddWorkShiftResponse> AddWorkShiftAsync(Project.AdminServiceReference.ArrayOfString details) {
            Project.AdminServiceReference.AddWorkShiftRequest inValue = new Project.AdminServiceReference.AddWorkShiftRequest();
            inValue.Body = new Project.AdminServiceReference.AddWorkShiftRequestBody();
            inValue.Body.details = details;
            return ((Project.AdminServiceReference.WebAdminSoap)(this)).AddWorkShiftAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project.AdminServiceReference.UpdateWorkShiftResponse Project.AdminServiceReference.WebAdminSoap.UpdateWorkShift(Project.AdminServiceReference.UpdateWorkShiftRequest request) {
            return base.Channel.UpdateWorkShift(request);
        }
        
        public bool UpdateWorkShift(Project.AdminServiceReference.ArrayOfString details, int workShiftId) {
            Project.AdminServiceReference.UpdateWorkShiftRequest inValue = new Project.AdminServiceReference.UpdateWorkShiftRequest();
            inValue.Body = new Project.AdminServiceReference.UpdateWorkShiftRequestBody();
            inValue.Body.details = details;
            inValue.Body.workShiftId = workShiftId;
            Project.AdminServiceReference.UpdateWorkShiftResponse retVal = ((Project.AdminServiceReference.WebAdminSoap)(this)).UpdateWorkShift(inValue);
            return retVal.Body.UpdateWorkShiftResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project.AdminServiceReference.UpdateWorkShiftResponse> Project.AdminServiceReference.WebAdminSoap.UpdateWorkShiftAsync(Project.AdminServiceReference.UpdateWorkShiftRequest request) {
            return base.Channel.UpdateWorkShiftAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project.AdminServiceReference.UpdateWorkShiftResponse> UpdateWorkShiftAsync(Project.AdminServiceReference.ArrayOfString details, int workShiftId) {
            Project.AdminServiceReference.UpdateWorkShiftRequest inValue = new Project.AdminServiceReference.UpdateWorkShiftRequest();
            inValue.Body = new Project.AdminServiceReference.UpdateWorkShiftRequestBody();
            inValue.Body.details = details;
            inValue.Body.workShiftId = workShiftId;
            return ((Project.AdminServiceReference.WebAdminSoap)(this)).UpdateWorkShiftAsync(inValue);
        }
        
        public bool DeleteWorkShift(int workShiftId) {
            return base.Channel.DeleteWorkShift(workShiftId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteWorkShiftAsync(int workShiftId) {
            return base.Channel.DeleteWorkShiftAsync(workShiftId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project.AdminServiceReference.GetAllSchedulesByCinemaResponse Project.AdminServiceReference.WebAdminSoap.GetAllSchedulesByCinema(Project.AdminServiceReference.GetAllSchedulesByCinemaRequest request) {
            return base.Channel.GetAllSchedulesByCinema(request);
        }
        
        public Project.AdminServiceReference.ArrayOfString GetAllSchedulesByCinema(int cinemaId) {
            Project.AdminServiceReference.GetAllSchedulesByCinemaRequest inValue = new Project.AdminServiceReference.GetAllSchedulesByCinemaRequest();
            inValue.Body = new Project.AdminServiceReference.GetAllSchedulesByCinemaRequestBody();
            inValue.Body.cinemaId = cinemaId;
            Project.AdminServiceReference.GetAllSchedulesByCinemaResponse retVal = ((Project.AdminServiceReference.WebAdminSoap)(this)).GetAllSchedulesByCinema(inValue);
            return retVal.Body.GetAllSchedulesByCinemaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project.AdminServiceReference.GetAllSchedulesByCinemaResponse> Project.AdminServiceReference.WebAdminSoap.GetAllSchedulesByCinemaAsync(Project.AdminServiceReference.GetAllSchedulesByCinemaRequest request) {
            return base.Channel.GetAllSchedulesByCinemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project.AdminServiceReference.GetAllSchedulesByCinemaResponse> GetAllSchedulesByCinemaAsync(int cinemaId) {
            Project.AdminServiceReference.GetAllSchedulesByCinemaRequest inValue = new Project.AdminServiceReference.GetAllSchedulesByCinemaRequest();
            inValue.Body = new Project.AdminServiceReference.GetAllSchedulesByCinemaRequestBody();
            inValue.Body.cinemaId = cinemaId;
            return ((Project.AdminServiceReference.WebAdminSoap)(this)).GetAllSchedulesByCinemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Project.AdminServiceReference.UpdateSchedulesResponse Project.AdminServiceReference.WebAdminSoap.UpdateSchedules(Project.AdminServiceReference.UpdateSchedulesRequest request) {
            return base.Channel.UpdateSchedules(request);
        }
        
        public bool UpdateSchedules(Project.AdminServiceReference.ArrayOfString details, int scheduleId) {
            Project.AdminServiceReference.UpdateSchedulesRequest inValue = new Project.AdminServiceReference.UpdateSchedulesRequest();
            inValue.Body = new Project.AdminServiceReference.UpdateSchedulesRequestBody();
            inValue.Body.details = details;
            inValue.Body.scheduleId = scheduleId;
            Project.AdminServiceReference.UpdateSchedulesResponse retVal = ((Project.AdminServiceReference.WebAdminSoap)(this)).UpdateSchedules(inValue);
            return retVal.Body.UpdateSchedulesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Project.AdminServiceReference.UpdateSchedulesResponse> Project.AdminServiceReference.WebAdminSoap.UpdateSchedulesAsync(Project.AdminServiceReference.UpdateSchedulesRequest request) {
            return base.Channel.UpdateSchedulesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Project.AdminServiceReference.UpdateSchedulesResponse> UpdateSchedulesAsync(Project.AdminServiceReference.ArrayOfString details, int scheduleId) {
            Project.AdminServiceReference.UpdateSchedulesRequest inValue = new Project.AdminServiceReference.UpdateSchedulesRequest();
            inValue.Body = new Project.AdminServiceReference.UpdateSchedulesRequestBody();
            inValue.Body.details = details;
            inValue.Body.scheduleId = scheduleId;
            return ((Project.AdminServiceReference.WebAdminSoap)(this)).UpdateSchedulesAsync(inValue);
        }
    }
}
