//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceTest.ServiceReference3 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference3.WebAdminSoap")]
    public interface WebAdminSoap {
        
        // CODEGEN: Generating message contract since element name GetAllMoviesDetailsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMoviesDetails", ReplyAction="*")]
        ServiceTest.ServiceReference3.GetAllMoviesDetailsResponse GetAllMoviesDetails(ServiceTest.ServiceReference3.GetAllMoviesDetailsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllMoviesDetails", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference3.GetAllMoviesDetailsResponse> GetAllMoviesDetailsAsync(ServiceTest.ServiceReference3.GetAllMoviesDetailsRequest request);
        
        // CODEGEN: Generating message contract since element name details from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMovie", ReplyAction="*")]
        ServiceTest.ServiceReference3.AddMovieResponse AddMovie(ServiceTest.ServiceReference3.AddMovieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddMovie", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference3.AddMovieResponse> AddMovieAsync(ServiceTest.ServiceReference3.AddMovieRequest request);
        
        // CODEGEN: Generating message contract since element name details from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMovie", ReplyAction="*")]
        ServiceTest.ServiceReference3.UpdateMovieResponse UpdateMovie(ServiceTest.ServiceReference3.UpdateMovieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateMovie", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference3.UpdateMovieResponse> UpdateMovieAsync(ServiceTest.ServiceReference3.UpdateMovieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMovie", ReplyAction="*")]
        bool DeleteMovie(int movieId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteMovie", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteMovieAsync(int movieId);
        
        // CODEGEN: Generating message contract since element name GetAllWorkShiftsResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllWorkShifts", ReplyAction="*")]
        ServiceTest.ServiceReference3.GetAllWorkShiftsResponse GetAllWorkShifts(ServiceTest.ServiceReference3.GetAllWorkShiftsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllWorkShifts", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference3.GetAllWorkShiftsResponse> GetAllWorkShiftsAsync(ServiceTest.ServiceReference3.GetAllWorkShiftsRequest request);
        
        // CODEGEN: Generating message contract since element name details from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddWorkShift", ReplyAction="*")]
        ServiceTest.ServiceReference3.AddWorkShiftResponse AddWorkShift(ServiceTest.ServiceReference3.AddWorkShiftRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddWorkShift", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference3.AddWorkShiftResponse> AddWorkShiftAsync(ServiceTest.ServiceReference3.AddWorkShiftRequest request);
        
        // CODEGEN: Generating message contract since element name details from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWorkShift", ReplyAction="*")]
        ServiceTest.ServiceReference3.UpdateWorkShiftResponse UpdateWorkShift(ServiceTest.ServiceReference3.UpdateWorkShiftRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateWorkShift", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference3.UpdateWorkShiftResponse> UpdateWorkShiftAsync(ServiceTest.ServiceReference3.UpdateWorkShiftRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteWorkShift", ReplyAction="*")]
        bool DeleteWorkShift(int workShiftId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteWorkShift", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteWorkShiftAsync(int workShiftId);
        
        // CODEGEN: Generating message contract since element name GetAllSchedulesByCinemaResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSchedulesByCinema", ReplyAction="*")]
        ServiceTest.ServiceReference3.GetAllSchedulesByCinemaResponse GetAllSchedulesByCinema(ServiceTest.ServiceReference3.GetAllSchedulesByCinemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllSchedulesByCinema", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference3.GetAllSchedulesByCinemaResponse> GetAllSchedulesByCinemaAsync(ServiceTest.ServiceReference3.GetAllSchedulesByCinemaRequest request);
        
        // CODEGEN: Generating message contract since element name details from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSchedules", ReplyAction="*")]
        ServiceTest.ServiceReference3.UpdateSchedulesResponse UpdateSchedules(ServiceTest.ServiceReference3.UpdateSchedulesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateSchedules", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference3.UpdateSchedulesResponse> UpdateSchedulesAsync(ServiceTest.ServiceReference3.UpdateSchedulesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCinemaIdByUserId", ReplyAction="*")]
        int GetCinemaIdByUserId(int userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCinemaIdByUserId", ReplyAction="*")]
        System.Threading.Tasks.Task<int> GetCinemaIdByUserIdAsync(int userId);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMoviesDetailsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMoviesDetails", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference3.GetAllMoviesDetailsRequestBody Body;
        
        public GetAllMoviesDetailsRequest() {
        }
        
        public GetAllMoviesDetailsRequest(ServiceTest.ServiceReference3.GetAllMoviesDetailsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllMoviesDetailsRequestBody {
        
        public GetAllMoviesDetailsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllMoviesDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllMoviesDetailsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference3.GetAllMoviesDetailsResponseBody Body;
        
        public GetAllMoviesDetailsResponse() {
        }
        
        public GetAllMoviesDetailsResponse(ServiceTest.ServiceReference3.GetAllMoviesDetailsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllMoviesDetailsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceTest.ServiceReference3.ArrayOfString GetAllMoviesDetailsResult;
        
        public GetAllMoviesDetailsResponseBody() {
        }
        
        public GetAllMoviesDetailsResponseBody(ServiceTest.ServiceReference3.ArrayOfString GetAllMoviesDetailsResult) {
            this.GetAllMoviesDetailsResult = GetAllMoviesDetailsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMovieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMovie", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference3.AddMovieRequestBody Body;
        
        public AddMovieRequest() {
        }
        
        public AddMovieRequest(ServiceTest.ServiceReference3.AddMovieRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMovieRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceTest.ServiceReference3.ArrayOfString details;
        
        public AddMovieRequestBody() {
        }
        
        public AddMovieRequestBody(ServiceTest.ServiceReference3.ArrayOfString details) {
            this.details = details;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddMovieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddMovieResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference3.AddMovieResponseBody Body;
        
        public AddMovieResponse() {
        }
        
        public AddMovieResponse(ServiceTest.ServiceReference3.AddMovieResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddMovieResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddMovieResult;
        
        public AddMovieResponseBody() {
        }
        
        public AddMovieResponseBody(bool AddMovieResult) {
            this.AddMovieResult = AddMovieResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMovieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMovie", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference3.UpdateMovieRequestBody Body;
        
        public UpdateMovieRequest() {
        }
        
        public UpdateMovieRequest(ServiceTest.ServiceReference3.UpdateMovieRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateMovieRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceTest.ServiceReference3.ArrayOfString details;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int movieId;
        
        public UpdateMovieRequestBody() {
        }
        
        public UpdateMovieRequestBody(ServiceTest.ServiceReference3.ArrayOfString details, int movieId) {
            this.details = details;
            this.movieId = movieId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateMovieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateMovieResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference3.UpdateMovieResponseBody Body;
        
        public UpdateMovieResponse() {
        }
        
        public UpdateMovieResponse(ServiceTest.ServiceReference3.UpdateMovieResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateMovieResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateMovieResult;
        
        public UpdateMovieResponseBody() {
        }
        
        public UpdateMovieResponseBody(bool UpdateMovieResult) {
            this.UpdateMovieResult = UpdateMovieResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllWorkShiftsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllWorkShifts", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference3.GetAllWorkShiftsRequestBody Body;
        
        public GetAllWorkShiftsRequest() {
        }
        
        public GetAllWorkShiftsRequest(ServiceTest.ServiceReference3.GetAllWorkShiftsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllWorkShiftsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cinemaId;
        
        public GetAllWorkShiftsRequestBody() {
        }
        
        public GetAllWorkShiftsRequestBody(int cinemaId) {
            this.cinemaId = cinemaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllWorkShiftsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllWorkShiftsResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference3.GetAllWorkShiftsResponseBody Body;
        
        public GetAllWorkShiftsResponse() {
        }
        
        public GetAllWorkShiftsResponse(ServiceTest.ServiceReference3.GetAllWorkShiftsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllWorkShiftsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceTest.ServiceReference3.ArrayOfString GetAllWorkShiftsResult;
        
        public GetAllWorkShiftsResponseBody() {
        }
        
        public GetAllWorkShiftsResponseBody(ServiceTest.ServiceReference3.ArrayOfString GetAllWorkShiftsResult) {
            this.GetAllWorkShiftsResult = GetAllWorkShiftsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddWorkShiftRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddWorkShift", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference3.AddWorkShiftRequestBody Body;
        
        public AddWorkShiftRequest() {
        }
        
        public AddWorkShiftRequest(ServiceTest.ServiceReference3.AddWorkShiftRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddWorkShiftRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceTest.ServiceReference3.ArrayOfString details;
        
        public AddWorkShiftRequestBody() {
        }
        
        public AddWorkShiftRequestBody(ServiceTest.ServiceReference3.ArrayOfString details) {
            this.details = details;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddWorkShiftResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddWorkShiftResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference3.AddWorkShiftResponseBody Body;
        
        public AddWorkShiftResponse() {
        }
        
        public AddWorkShiftResponse(ServiceTest.ServiceReference3.AddWorkShiftResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddWorkShiftResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddWorkShiftResult;
        
        public AddWorkShiftResponseBody() {
        }
        
        public AddWorkShiftResponseBody(bool AddWorkShiftResult) {
            this.AddWorkShiftResult = AddWorkShiftResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateWorkShiftRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateWorkShift", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference3.UpdateWorkShiftRequestBody Body;
        
        public UpdateWorkShiftRequest() {
        }
        
        public UpdateWorkShiftRequest(ServiceTest.ServiceReference3.UpdateWorkShiftRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateWorkShiftRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceTest.ServiceReference3.ArrayOfString details;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int workShiftId;
        
        public UpdateWorkShiftRequestBody() {
        }
        
        public UpdateWorkShiftRequestBody(ServiceTest.ServiceReference3.ArrayOfString details, int workShiftId) {
            this.details = details;
            this.workShiftId = workShiftId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateWorkShiftResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateWorkShiftResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference3.UpdateWorkShiftResponseBody Body;
        
        public UpdateWorkShiftResponse() {
        }
        
        public UpdateWorkShiftResponse(ServiceTest.ServiceReference3.UpdateWorkShiftResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateWorkShiftResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateWorkShiftResult;
        
        public UpdateWorkShiftResponseBody() {
        }
        
        public UpdateWorkShiftResponseBody(bool UpdateWorkShiftResult) {
            this.UpdateWorkShiftResult = UpdateWorkShiftResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSchedulesByCinemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSchedulesByCinema", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference3.GetAllSchedulesByCinemaRequestBody Body;
        
        public GetAllSchedulesByCinemaRequest() {
        }
        
        public GetAllSchedulesByCinemaRequest(ServiceTest.ServiceReference3.GetAllSchedulesByCinemaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllSchedulesByCinemaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int cinemaId;
        
        public GetAllSchedulesByCinemaRequestBody() {
        }
        
        public GetAllSchedulesByCinemaRequestBody(int cinemaId) {
            this.cinemaId = cinemaId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllSchedulesByCinemaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllSchedulesByCinemaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference3.GetAllSchedulesByCinemaResponseBody Body;
        
        public GetAllSchedulesByCinemaResponse() {
        }
        
        public GetAllSchedulesByCinemaResponse(ServiceTest.ServiceReference3.GetAllSchedulesByCinemaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllSchedulesByCinemaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceTest.ServiceReference3.ArrayOfString GetAllSchedulesByCinemaResult;
        
        public GetAllSchedulesByCinemaResponseBody() {
        }
        
        public GetAllSchedulesByCinemaResponseBody(ServiceTest.ServiceReference3.ArrayOfString GetAllSchedulesByCinemaResult) {
            this.GetAllSchedulesByCinemaResult = GetAllSchedulesByCinemaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSchedulesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSchedules", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference3.UpdateSchedulesRequestBody Body;
        
        public UpdateSchedulesRequest() {
        }
        
        public UpdateSchedulesRequest(ServiceTest.ServiceReference3.UpdateSchedulesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSchedulesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiceTest.ServiceReference3.ArrayOfString details;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int scheduleId;
        
        public UpdateSchedulesRequestBody() {
        }
        
        public UpdateSchedulesRequestBody(ServiceTest.ServiceReference3.ArrayOfString details, int scheduleId) {
            this.details = details;
            this.scheduleId = scheduleId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateSchedulesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateSchedulesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceTest.ServiceReference3.UpdateSchedulesResponseBody Body;
        
        public UpdateSchedulesResponse() {
        }
        
        public UpdateSchedulesResponse(ServiceTest.ServiceReference3.UpdateSchedulesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateSchedulesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateSchedulesResult;
        
        public UpdateSchedulesResponseBody() {
        }
        
        public UpdateSchedulesResponseBody(bool UpdateSchedulesResult) {
            this.UpdateSchedulesResult = UpdateSchedulesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebAdminSoapChannel : ServiceTest.ServiceReference3.WebAdminSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebAdminSoapClient : System.ServiceModel.ClientBase<ServiceTest.ServiceReference3.WebAdminSoap>, ServiceTest.ServiceReference3.WebAdminSoap {
        
        public WebAdminSoapClient() {
        }
        
        public WebAdminSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebAdminSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebAdminSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebAdminSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.ServiceReference3.GetAllMoviesDetailsResponse ServiceTest.ServiceReference3.WebAdminSoap.GetAllMoviesDetails(ServiceTest.ServiceReference3.GetAllMoviesDetailsRequest request) {
            return base.Channel.GetAllMoviesDetails(request);
        }
        
        public ServiceTest.ServiceReference3.ArrayOfString GetAllMoviesDetails() {
            ServiceTest.ServiceReference3.GetAllMoviesDetailsRequest inValue = new ServiceTest.ServiceReference3.GetAllMoviesDetailsRequest();
            inValue.Body = new ServiceTest.ServiceReference3.GetAllMoviesDetailsRequestBody();
            ServiceTest.ServiceReference3.GetAllMoviesDetailsResponse retVal = ((ServiceTest.ServiceReference3.WebAdminSoap)(this)).GetAllMoviesDetails(inValue);
            return retVal.Body.GetAllMoviesDetailsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference3.GetAllMoviesDetailsResponse> ServiceTest.ServiceReference3.WebAdminSoap.GetAllMoviesDetailsAsync(ServiceTest.ServiceReference3.GetAllMoviesDetailsRequest request) {
            return base.Channel.GetAllMoviesDetailsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.ServiceReference3.GetAllMoviesDetailsResponse> GetAllMoviesDetailsAsync() {
            ServiceTest.ServiceReference3.GetAllMoviesDetailsRequest inValue = new ServiceTest.ServiceReference3.GetAllMoviesDetailsRequest();
            inValue.Body = new ServiceTest.ServiceReference3.GetAllMoviesDetailsRequestBody();
            return ((ServiceTest.ServiceReference3.WebAdminSoap)(this)).GetAllMoviesDetailsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.ServiceReference3.AddMovieResponse ServiceTest.ServiceReference3.WebAdminSoap.AddMovie(ServiceTest.ServiceReference3.AddMovieRequest request) {
            return base.Channel.AddMovie(request);
        }
        
        public bool AddMovie(ServiceTest.ServiceReference3.ArrayOfString details) {
            ServiceTest.ServiceReference3.AddMovieRequest inValue = new ServiceTest.ServiceReference3.AddMovieRequest();
            inValue.Body = new ServiceTest.ServiceReference3.AddMovieRequestBody();
            inValue.Body.details = details;
            ServiceTest.ServiceReference3.AddMovieResponse retVal = ((ServiceTest.ServiceReference3.WebAdminSoap)(this)).AddMovie(inValue);
            return retVal.Body.AddMovieResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference3.AddMovieResponse> ServiceTest.ServiceReference3.WebAdminSoap.AddMovieAsync(ServiceTest.ServiceReference3.AddMovieRequest request) {
            return base.Channel.AddMovieAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.ServiceReference3.AddMovieResponse> AddMovieAsync(ServiceTest.ServiceReference3.ArrayOfString details) {
            ServiceTest.ServiceReference3.AddMovieRequest inValue = new ServiceTest.ServiceReference3.AddMovieRequest();
            inValue.Body = new ServiceTest.ServiceReference3.AddMovieRequestBody();
            inValue.Body.details = details;
            return ((ServiceTest.ServiceReference3.WebAdminSoap)(this)).AddMovieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.ServiceReference3.UpdateMovieResponse ServiceTest.ServiceReference3.WebAdminSoap.UpdateMovie(ServiceTest.ServiceReference3.UpdateMovieRequest request) {
            return base.Channel.UpdateMovie(request);
        }
        
        public bool UpdateMovie(ServiceTest.ServiceReference3.ArrayOfString details, int movieId) {
            ServiceTest.ServiceReference3.UpdateMovieRequest inValue = new ServiceTest.ServiceReference3.UpdateMovieRequest();
            inValue.Body = new ServiceTest.ServiceReference3.UpdateMovieRequestBody();
            inValue.Body.details = details;
            inValue.Body.movieId = movieId;
            ServiceTest.ServiceReference3.UpdateMovieResponse retVal = ((ServiceTest.ServiceReference3.WebAdminSoap)(this)).UpdateMovie(inValue);
            return retVal.Body.UpdateMovieResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference3.UpdateMovieResponse> ServiceTest.ServiceReference3.WebAdminSoap.UpdateMovieAsync(ServiceTest.ServiceReference3.UpdateMovieRequest request) {
            return base.Channel.UpdateMovieAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.ServiceReference3.UpdateMovieResponse> UpdateMovieAsync(ServiceTest.ServiceReference3.ArrayOfString details, int movieId) {
            ServiceTest.ServiceReference3.UpdateMovieRequest inValue = new ServiceTest.ServiceReference3.UpdateMovieRequest();
            inValue.Body = new ServiceTest.ServiceReference3.UpdateMovieRequestBody();
            inValue.Body.details = details;
            inValue.Body.movieId = movieId;
            return ((ServiceTest.ServiceReference3.WebAdminSoap)(this)).UpdateMovieAsync(inValue);
        }
        
        public bool DeleteMovie(int movieId) {
            return base.Channel.DeleteMovie(movieId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteMovieAsync(int movieId) {
            return base.Channel.DeleteMovieAsync(movieId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.ServiceReference3.GetAllWorkShiftsResponse ServiceTest.ServiceReference3.WebAdminSoap.GetAllWorkShifts(ServiceTest.ServiceReference3.GetAllWorkShiftsRequest request) {
            return base.Channel.GetAllWorkShifts(request);
        }
        
        public ServiceTest.ServiceReference3.ArrayOfString GetAllWorkShifts(int cinemaId) {
            ServiceTest.ServiceReference3.GetAllWorkShiftsRequest inValue = new ServiceTest.ServiceReference3.GetAllWorkShiftsRequest();
            inValue.Body = new ServiceTest.ServiceReference3.GetAllWorkShiftsRequestBody();
            inValue.Body.cinemaId = cinemaId;
            ServiceTest.ServiceReference3.GetAllWorkShiftsResponse retVal = ((ServiceTest.ServiceReference3.WebAdminSoap)(this)).GetAllWorkShifts(inValue);
            return retVal.Body.GetAllWorkShiftsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference3.GetAllWorkShiftsResponse> ServiceTest.ServiceReference3.WebAdminSoap.GetAllWorkShiftsAsync(ServiceTest.ServiceReference3.GetAllWorkShiftsRequest request) {
            return base.Channel.GetAllWorkShiftsAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.ServiceReference3.GetAllWorkShiftsResponse> GetAllWorkShiftsAsync(int cinemaId) {
            ServiceTest.ServiceReference3.GetAllWorkShiftsRequest inValue = new ServiceTest.ServiceReference3.GetAllWorkShiftsRequest();
            inValue.Body = new ServiceTest.ServiceReference3.GetAllWorkShiftsRequestBody();
            inValue.Body.cinemaId = cinemaId;
            return ((ServiceTest.ServiceReference3.WebAdminSoap)(this)).GetAllWorkShiftsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.ServiceReference3.AddWorkShiftResponse ServiceTest.ServiceReference3.WebAdminSoap.AddWorkShift(ServiceTest.ServiceReference3.AddWorkShiftRequest request) {
            return base.Channel.AddWorkShift(request);
        }
        
        public bool AddWorkShift(ServiceTest.ServiceReference3.ArrayOfString details) {
            ServiceTest.ServiceReference3.AddWorkShiftRequest inValue = new ServiceTest.ServiceReference3.AddWorkShiftRequest();
            inValue.Body = new ServiceTest.ServiceReference3.AddWorkShiftRequestBody();
            inValue.Body.details = details;
            ServiceTest.ServiceReference3.AddWorkShiftResponse retVal = ((ServiceTest.ServiceReference3.WebAdminSoap)(this)).AddWorkShift(inValue);
            return retVal.Body.AddWorkShiftResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference3.AddWorkShiftResponse> ServiceTest.ServiceReference3.WebAdminSoap.AddWorkShiftAsync(ServiceTest.ServiceReference3.AddWorkShiftRequest request) {
            return base.Channel.AddWorkShiftAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.ServiceReference3.AddWorkShiftResponse> AddWorkShiftAsync(ServiceTest.ServiceReference3.ArrayOfString details) {
            ServiceTest.ServiceReference3.AddWorkShiftRequest inValue = new ServiceTest.ServiceReference3.AddWorkShiftRequest();
            inValue.Body = new ServiceTest.ServiceReference3.AddWorkShiftRequestBody();
            inValue.Body.details = details;
            return ((ServiceTest.ServiceReference3.WebAdminSoap)(this)).AddWorkShiftAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.ServiceReference3.UpdateWorkShiftResponse ServiceTest.ServiceReference3.WebAdminSoap.UpdateWorkShift(ServiceTest.ServiceReference3.UpdateWorkShiftRequest request) {
            return base.Channel.UpdateWorkShift(request);
        }
        
        public bool UpdateWorkShift(ServiceTest.ServiceReference3.ArrayOfString details, int workShiftId) {
            ServiceTest.ServiceReference3.UpdateWorkShiftRequest inValue = new ServiceTest.ServiceReference3.UpdateWorkShiftRequest();
            inValue.Body = new ServiceTest.ServiceReference3.UpdateWorkShiftRequestBody();
            inValue.Body.details = details;
            inValue.Body.workShiftId = workShiftId;
            ServiceTest.ServiceReference3.UpdateWorkShiftResponse retVal = ((ServiceTest.ServiceReference3.WebAdminSoap)(this)).UpdateWorkShift(inValue);
            return retVal.Body.UpdateWorkShiftResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference3.UpdateWorkShiftResponse> ServiceTest.ServiceReference3.WebAdminSoap.UpdateWorkShiftAsync(ServiceTest.ServiceReference3.UpdateWorkShiftRequest request) {
            return base.Channel.UpdateWorkShiftAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.ServiceReference3.UpdateWorkShiftResponse> UpdateWorkShiftAsync(ServiceTest.ServiceReference3.ArrayOfString details, int workShiftId) {
            ServiceTest.ServiceReference3.UpdateWorkShiftRequest inValue = new ServiceTest.ServiceReference3.UpdateWorkShiftRequest();
            inValue.Body = new ServiceTest.ServiceReference3.UpdateWorkShiftRequestBody();
            inValue.Body.details = details;
            inValue.Body.workShiftId = workShiftId;
            return ((ServiceTest.ServiceReference3.WebAdminSoap)(this)).UpdateWorkShiftAsync(inValue);
        }
        
        public bool DeleteWorkShift(int workShiftId) {
            return base.Channel.DeleteWorkShift(workShiftId);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteWorkShiftAsync(int workShiftId) {
            return base.Channel.DeleteWorkShiftAsync(workShiftId);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.ServiceReference3.GetAllSchedulesByCinemaResponse ServiceTest.ServiceReference3.WebAdminSoap.GetAllSchedulesByCinema(ServiceTest.ServiceReference3.GetAllSchedulesByCinemaRequest request) {
            return base.Channel.GetAllSchedulesByCinema(request);
        }
        
        public ServiceTest.ServiceReference3.ArrayOfString GetAllSchedulesByCinema(int cinemaId) {
            ServiceTest.ServiceReference3.GetAllSchedulesByCinemaRequest inValue = new ServiceTest.ServiceReference3.GetAllSchedulesByCinemaRequest();
            inValue.Body = new ServiceTest.ServiceReference3.GetAllSchedulesByCinemaRequestBody();
            inValue.Body.cinemaId = cinemaId;
            ServiceTest.ServiceReference3.GetAllSchedulesByCinemaResponse retVal = ((ServiceTest.ServiceReference3.WebAdminSoap)(this)).GetAllSchedulesByCinema(inValue);
            return retVal.Body.GetAllSchedulesByCinemaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference3.GetAllSchedulesByCinemaResponse> ServiceTest.ServiceReference3.WebAdminSoap.GetAllSchedulesByCinemaAsync(ServiceTest.ServiceReference3.GetAllSchedulesByCinemaRequest request) {
            return base.Channel.GetAllSchedulesByCinemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.ServiceReference3.GetAllSchedulesByCinemaResponse> GetAllSchedulesByCinemaAsync(int cinemaId) {
            ServiceTest.ServiceReference3.GetAllSchedulesByCinemaRequest inValue = new ServiceTest.ServiceReference3.GetAllSchedulesByCinemaRequest();
            inValue.Body = new ServiceTest.ServiceReference3.GetAllSchedulesByCinemaRequestBody();
            inValue.Body.cinemaId = cinemaId;
            return ((ServiceTest.ServiceReference3.WebAdminSoap)(this)).GetAllSchedulesByCinemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiceTest.ServiceReference3.UpdateSchedulesResponse ServiceTest.ServiceReference3.WebAdminSoap.UpdateSchedules(ServiceTest.ServiceReference3.UpdateSchedulesRequest request) {
            return base.Channel.UpdateSchedules(request);
        }
        
        public bool UpdateSchedules(ServiceTest.ServiceReference3.ArrayOfString details, int scheduleId) {
            ServiceTest.ServiceReference3.UpdateSchedulesRequest inValue = new ServiceTest.ServiceReference3.UpdateSchedulesRequest();
            inValue.Body = new ServiceTest.ServiceReference3.UpdateSchedulesRequestBody();
            inValue.Body.details = details;
            inValue.Body.scheduleId = scheduleId;
            ServiceTest.ServiceReference3.UpdateSchedulesResponse retVal = ((ServiceTest.ServiceReference3.WebAdminSoap)(this)).UpdateSchedules(inValue);
            return retVal.Body.UpdateSchedulesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceTest.ServiceReference3.UpdateSchedulesResponse> ServiceTest.ServiceReference3.WebAdminSoap.UpdateSchedulesAsync(ServiceTest.ServiceReference3.UpdateSchedulesRequest request) {
            return base.Channel.UpdateSchedulesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceTest.ServiceReference3.UpdateSchedulesResponse> UpdateSchedulesAsync(ServiceTest.ServiceReference3.ArrayOfString details, int scheduleId) {
            ServiceTest.ServiceReference3.UpdateSchedulesRequest inValue = new ServiceTest.ServiceReference3.UpdateSchedulesRequest();
            inValue.Body = new ServiceTest.ServiceReference3.UpdateSchedulesRequestBody();
            inValue.Body.details = details;
            inValue.Body.scheduleId = scheduleId;
            return ((ServiceTest.ServiceReference3.WebAdminSoap)(this)).UpdateSchedulesAsync(inValue);
        }
        
        public int GetCinemaIdByUserId(int userId) {
            return base.Channel.GetCinemaIdByUserId(userId);
        }
        
        public System.Threading.Tasks.Task<int> GetCinemaIdByUserIdAsync(int userId) {
            return base.Channel.GetCinemaIdByUserIdAsync(userId);
        }
    }
}
